package sos.scheduler.jade;


/**
* \class JadeJob
*
* \brief JadeJob -
*
* \details
*
* \code
*   .... code goes here ...
* \endcode
*
* <p style="text-align:center">
* <br />---------------------------------------------------------------------------
* <br /> APL/Software GmbH - Berlin
* <br />##### generated by ClaviusXPress (http://www.sos-berlin.com) #########
* <br />---------------------------------------------------------------------------
* </p>
* \author Uwe Risse
* \version 03.08.2011
* \see reference
*
* Created on 03.08.2011 13:51:09
 */

public class Jade4DMZJob extends SOSJade4DMZJSAdapter {

	@SuppressWarnings("unused")
	private final String	conSVNVersion	= "$Id: Jade4DMZJob.java 17751 2012-08-03 11:51:07Z kb $";
	@SuppressWarnings("unused")
	private final String conClassName = this.getClass().getName();

	Jade4DMZJob() {
		super();
	}
}
