package sos.jadehistory.db;

/**
* \class TestFtpFilesHistory 
* 
* \brief TestHistorie - 
* 
* \details
*
* \section TestHistorie.java_intro_sec Introduction
*
* \section TestHistorie.java_samples Some Samples
*
* \code
*   .... code goes here ...
* \endcode
*
* <p style="text-align:center">
* <br />---------------------------------------------------------------------------
* <br /> APL/Software GmbH - Berlin
* <br />##### generated by ClaviusXPress (http://www.sos-berlin.com) #########
* <br />---------------------------------------------------------------------------
* </p>
* \author Uwe Risse
* \version 15.06.2011
* \see reference
*
* Created on 15.06.2011 15:06:50
 */

import static org.junit.Assert.assertNotNull;

import java.io.File;
import java.util.List;

import org.hibernate.Query;
import org.junit.After;
import org.junit.AfterClass;
import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Ignore;
import org.junit.Test;

import com.sos.hibernate.classes.DbItem;

//oh 18.04.14 No runnable methods [SP]
@Ignore("Test set to Ignore for later examination") //comment this to run tests locally
//11.08.15 runnable test methods added [SP] 
public class TestJadeFilesHistorie {
 
	private String configurationFilename = "c:/temp/hibernate.cfg.xml";
	private File configurationFile;

	public TestJadeFilesHistorie() {
	}

	@BeforeClass
	public static void setUpBeforeClass() throws Exception {
	}

	@AfterClass
	public static void tearDownAfterClass() throws Exception {
	}

	@Before
	public void setUp() throws Exception {
	}

	@After
	public void tearDown() throws Exception {
	}

	@Test
	public void testPartialSearchword(){
		JadeFilesDBLayer layer = new JadeFilesDBLayer(configurationFilename);
        try {
        	layer.getConnection().connect();
        	layer.getConnection().beginTransaction();
			Query query = layer.getConnection().createQuery(" from JadeFilesDBItem where sourceFilename like '%Mass%'");
			List<DbItem> resultset = query.list();
			assertNotNull(resultset);
			for(DbItem item : resultset){
				System.out.println("**** sourceFilename: " + ((JadeFilesDBItem)item).getSourceFilename() + "****");
			}
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

	@Test
	public void testCompleteSearchword(){
		JadeFilesDBLayer layer = new JadeFilesDBLayer(configurationFilename);
        try {
        	layer.getConnection().connect();
        	layer.getConnection().beginTransaction();
			Query query = layer.getConnection().createQuery(" from JadeFilesDBItem where sourceFilename = 'Masstest00001.txt'");
			List<DbItem> resultset = query.list();
			assertNotNull(resultset);
			for(DbItem item : resultset){
				System.out.println("**** sourceFilename: " + ((JadeFilesDBItem)item).getSourceFilename() + "****");
			}
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

}
