package sos.scheduler.job;

/**
* \class SOSDataExchange 
* 
* \brief SOSDataExchange - 
* 
* \details
*
* \section SOSDataExchange.java_intro_sec Introduction
*
* \section SOSDataExchange.java_samples Some Samples
*
* \code
*   .... code goes here ...
* \endcode
*
* <p style="text-align:center">
* <br />---------------------------------------------------------------------------
* <br /> APL/Software GmbH - Berlin
* <br />##### generated by ClaviusXPress (http://www.sos-berlin.com) #########
* <br />---------------------------------------------------------------------------
* </p>
* \author Uwe Risse
* \version 03.08.2011
* \see reference
*
* Created on 03.08.2011 13:51:09
 */

public class SOSDataExchange extends SOSDExJSAdapterClass {

	@SuppressWarnings("unused")
	private final String	conClassName	= "SOSDataExchange";

	SOSDataExchange() {
		super();
	}
}
