package com.sos.jade.classes;

import org.eclipse.swt.widgets.Table;
import org.eclipse.swt.widgets.TableItem;

import com.sos.jade.db.JadeTransferDBItem;

/** \class JadeHistoryTableItem
 * 
 * \brief JadeHistoryTableItem -
 * 
 * \details
 *
 * \section JadeHistoryTableItem.java_intro_sec Introduction
 *
 * \section JadeHistoryTableItem.java_samples Some Samples
 *
 * \code .... code goes here ... \endcode
 *
 * <p style="text-align:center">
 * <br />
 * --------------------------------------------------------------------------- <br />
 * APL/Software GmbH - Berlin <br />
 * ##### generated by ClaviusXPress (http://www.sos-berlin.com) ######### <br />
 * ---------------------------------------------------------------------------
 * </p>
 * \author Uwe Risse \version 14.12.2011 \see reference
 *
 * Created on 14.12.2011 13:51:13 */

public class JadeHistoryTableItem extends TableItem {

    private JadeTransferDBItem jadeTransferDBItem = null;
    private String[] textBuffer = null;

    public JadeHistoryTableItem(Table arg0, int arg1) {
        super(arg0, arg1);
    }

    protected void checkSubclass() {
        // Disable the check that prevents subclassing of SWT components
    }

    public void setJadeHistoryDBItem(JadeTransferDBItem d) {
        jadeTransferDBItem = d;
        this.setData(d);
    }

    public void setColumns() {
        JadeTransferDBItem h = jadeTransferDBItem;

        textBuffer = new String[] { h.getProfileName(), h.getSourceDir(), h.getTargetDir(), h.getStartTimeIso(), h.getEndTimeIso(),
                String.valueOf(h.getStatusValue()), };
        this.setText(textBuffer);
    }

    public String[] getTextBuffer() {
        return textBuffer;
    }

    @SuppressWarnings("unused")
    private final String conClassName = "JadeHistoryTableItem";

}
