package com.sos.jade.classes;

/** \class JadeTransferProtocolType
 * 
 * \brief JadeTransferProtocolType -
 * 
 * \details
 *
 * \section JadeTransferProtocolType.java_intro_sec Introduction
 *
 * \section JadeTransferProtocolType.java_samples Some Samples
 *
 * \code .... code goes here ... \endcode
 *
 * <p style="text-align:center">
 * <br />
 * --------------------------------------------------------------------------- <br />
 * APL/Software GmbH - Berlin <br />
 * ##### generated by ClaviusXPress (http://www.sos-berlin.com) ######### <br />
 * ---------------------------------------------------------------------------
 * </p>
 * \author Uwe Risse \version 21.09.2011 \see reference
 *
 * Created on 21.09.2011 11:05:32 */

public class JadeTransferProtocolType {

    @SuppressWarnings("unused")
    private final String conClassName = "JadeTransferProtocolType";
    private int protocolType;
    private String[] protocolTypeIdentifier = { "ftp", "sftp", "ftps" };

    public JadeTransferProtocolType() {
        //
    }

    public String getProtocolType(int protocolType_) throws Exception {
        if (protocolType_ > protocolTypeIdentifier.length) {
            throw new Exception("Unknown protocol type index " + protocolType_);
        } else {
            return protocolTypeIdentifier[protocolType_];
        }
    }

    public int getProtocolType() {
        return protocolType;
    }

    public void setProtocolType(String protocolType_) throws Exception {
        for (int i = 0; i < protocolTypeIdentifier.length; i++) {
            if (protocolTypeIdentifier[i].equalsIgnoreCase(protocolType_)) {
                this.protocolType = i;
            }
        }
        throw new Exception(String.format("Protocol type %1 not found", protocolType_));
    }

    public void setProtocolType(int protocolType_) {
        this.protocolType = protocolType_;
    }

}
