package com.sos.jade.classes;

/** \class JadeTransferStatus
 * 
 * \brief JadeTransferStatus -
 * 
 * \details
 *
 * \section JadeTransferStatus.java_intro_sec Introduction
 *
 * \section JadeTransferStatus.java_samples Some Samples
 *
 * \code .... code goes here ... \endcode
 *
 * <p style="text-align:center">
 * <br />
 * --------------------------------------------------------------------------- <br />
 * APL/Software GmbH - Berlin <br />
 * ##### generated by ClaviusXPress (http://www.sos-berlin.com) ######### <br />
 * ---------------------------------------------------------------------------
 * </p>
 * \author Uwe Risse \version 21.09.2011 \see reference
 *
 * Created on 21.09.2011 11:05:32 */

public class JadeTransferStatus {

    @SuppressWarnings("unused")
    private final String conClassName = "JadeTransferStatus";
    private int status;
    private String[] statusIdentifier = { "success", "error" };

    public JadeTransferStatus() {
        //
    }

    public String getStatus(int status_) throws Exception {
        if (status_ > statusIdentifier.length) {
            throw new Exception("Unknown status index " + status_);
        } else {
            return statusIdentifier[status_];
        }
    }

    public int getStatus() {
        return status;
    }

    public void setStatus(String status_) throws Exception {
        for (int i = 0; i < statusIdentifier.length; i++) {
            if (statusIdentifier[i].equalsIgnoreCase(status_)) {
                this.status = i;
            }
        }
        throw new Exception(String.format("Status %1 not found", status_));
    }

    public void setStatus(int status_) {
        this.status = status_;
    }

}
