package com.sos.jade;

import java.io.File;
 
import java.util.Iterator;
import java.util.List;

import org.apache.log4j.Logger;
import org.eclipse.swt.SWT;
import org.eclipse.swt.widgets.Table;

import com.sos.jade.db.JadeTransferDBItem;
import com.sos.jade.db.JadeTransferDBLayer;
import com.sos.jade.classes.JadeHistoryTableItem;
import com.sos.hibernate.classes.DbItem;
import com.sos.hibernate.interfaces.ISOSHibernateDataProvider;

/**
* \class JadeHistoryDataProvider 
* 
* \brief JadeHistoryDataProvider - 
* 
* \details
*
* \section JadeHistoryDataProvider.java_intro_sec Introduction
*
* \section JadeHistoryDataProvider.java_samples Some Samples
*
* \code
*   .... code goes here ...
* \endcode
*
* <p style="text-align:center">
* <br />---------------------------------------------------------------------------
* <br /> APL/Software GmbH - Berlin
* <br />##### generated by ClaviusXPress (http://www.sos-berlin.com) #########
* <br />---------------------------------------------------------------------------
* </p>
* \author Uwe Risse
* \version 19.01.2012
* \see reference
*
* Created on 19.01.2012 09:31:01
 */

public class JadeHistoryDataProvider implements ISOSHibernateDataProvider{

	@SuppressWarnings("unused")
	private final String	conClassName	= "JadeHistoryDataProvider";

	private List <JadeTransferDBItem> listOfTransferItems; 
	private JadeTransferDBLayer       jadeTransferDBLayer;
	private static Logger		      logger = Logger.getLogger(JadeHistoryDataProvider.class);
	private Table           	      tableTransfers = null;
	
    
	public JadeHistoryDataProvider(File configurationFile) {
		this.jadeTransferDBLayer = new JadeTransferDBLayer(configurationFile.getAbsolutePath());
	}
	
    public JadeHistoryFilter getFilter() {
    	return jadeTransferDBLayer.getFilter();
    }
    
    public void resetFilter() {
    	jadeTransferDBLayer.setFilter(new JadeHistoryFilter());
    }

	public void getData(int limit) {
		listOfTransferItems = jadeTransferDBLayer.getTransferList(limit);
	}

	@Override
	public void fillTable(Table table) {
		// TODO Auto-generated method stub
		
	}

}
